function [ models_desc ] = load_models_desc
% Load Models' Description

models_desc = {            ...
struct( 'name',          'cppca_svd',                     ...
        'type',          'cppca',                         ...
        'desc',          'svd',                           ...
        'fn',            @cppca,                          ...
        'mat_result',    'cppca_svd.mat',                 ...
        'skip',          1),                              ...
                                                          ...
struct( 'name',          'cppca_em',                      ...
        'type',          'cppca',                         ...
        'desc',          'em',                            ...
        'fn',            @cppca_em,                       ...
        'mat_result',    'cppca_em.mat',                  ...
        'skip',          1),                              ...
                                                          ...
struct( 'name',          'cppca_affine',                  ...
        'type',          'cppca',                         ...
        'desc',          'affine',                        ...
        'fn',            @sfm_affine,                     ...
        'mat_result',    'cppca_affine.mat',              ...
        'skip',          1),                              ...
                                                          ...
struct( 'name',          'dppca',                         ...
        'type',          'dppca',                         ...
        'desc',          '',                              ...
        'fn',            @dppca,                          ...
        'mat_result',    'dppca.mat',                     ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_AP_hetero',               ...
        'type',          'dppca',                         ...
        'desc',          'dppca_AP_hetero',               ...
        'fn',            @dppca_ant  ,                    ...
        'mat_result',    'dppca_AP_hetero.mat',           ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_AP_homo',                 ...
        'type',          'dppca',                         ...
        'desc',          'dppca_AP_homo',                 ...
        'fn',            @dppca_ant  ,                    ...
        'mat_result',    'dppca_AP_homo.mat',             ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_NAP_hetero',              ...
        'type',          'dppca',                         ...
        'desc',          'dppca_NAP_hetero',              ...
        'fn',            @dppca_ant  ,                    ...
        'mat_result',    'dppca_NAP_hetero.mat',          ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_NAP_homo',                ...
        'type',          'dppca',                         ...
        'desc',          'dppca_NAP_homo',                ...
        'fn',            @dppca_ant  ,                    ...
        'mat_result',    'dppca_NAP_homo.mat',            ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_vp',                      ...
        'type',          'dppca',                         ...
        'desc',          'dppca_vp',                      ...
        'fn',            @dppca,                          ...
        'mat_result',    'dppca_vp.mat',                  ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_localVP_hetero',          ...
        'type',          'dppca',                         ...
        'desc',          'dppca_localVP_hetero',          ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_localVP_hetero.mat',        ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_localVP_homo',            ...
        'type',          'dppca',                         ...
        'desc',          'dppca_localVP_homo',            ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_localVP_homo.mat',        ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_localVPAP_hetero',        ...
        'type',          'dppca',                         ...
        'desc',          'dppca_localVPAP_hetero',        ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_localVPAP_hetero.mat',    ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_localVPAP_homo',          ...
        'type',          'dppca',                         ...
        'desc',          'dppca_localVPAP_homo',          ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_localVPAP_homo.mat',      ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_localVPNAP_hetero',       ...
        'type',          'dppca',                         ...
        'desc',          'dppca_localVPNAP_hetero',       ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_localVPNAP_hetero.mat',   ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_localVPNAP_homo',         ...
        'type',          'dppca',                         ...
        'desc',          'dppca_localVPNAP_homo',         ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_localVPNAP_homo.mat',     ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'fadmm',                         ...
        'type',          'dppca',                         ...
        'desc',          'fadmm',                         ...
        'fn',            @dppca,                          ...
        'mat_result',    'fadmm.mat',                     ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_globalFRS',               ...
        'type',          'dppca',                         ...
        'desc',          'dppca_globalFRS',               ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_globalFRS.mat',           ...
        'skip',          0),                              ...
                                                          ...
struct( 'name',          'dppca_localFRS',                ...
        'type',          'dppca',                         ...
        'desc',          'dppca_localFRS',                ...
        'fn',            @dppca_ant,                      ...
        'mat_result',    'dppca_localFRS.mat',            ...
        'skip',          0),                              ...
                                                          ...
};

end

