function [ model ] = parfor_dppca( model_desc, varargin )

X                  = varargin{1};
dim_Z              = varargin{2};
W_GT               = varargin{3};
b_zeromean_expr    = varargin{4};

ETA                = varargin{5};
Vp                 = varargin{6};
adj_Network        = varargin{7};

objprec_expr       = varargin{8};
objfreq_expr       = varargin{9};
init_model         = varargin{10};

desc_name  = model_desc.name;
desc_model = model_desc.desc;
fn_model   = model_desc.fn;

if( isequal( desc_name, 'dppca' ) )
     model ...
     = feval(     fn_model, X, dim_Z,             ...
                  Vp, adj_Network,                ...
                  'W_GT',        W_GT,            ...
                  'ZeroMean',    b_zeromean_expr, ...    
                  'Eta',         ETA,             ...                  
                  'Threshold',   objprec_expr,    ...
                  'ShowObjPer',  objfreq_expr,    ...
                  'MaxIter',     1000,            ...
                  'UseResidual', false,           ...                  
                  'InitModel',   init_model );

elseif( isequal( desc_name, 'fadmm' ) )
    model ...
     = feval(     fn_model, X, dim_Z,           ...
                  Vp, adj_Network,              ...
                  'W_GT',       W_GT,           ...
                  'ZeroMean',   b_zeromean_expr,...    
                  'Eta',       ETA,             ...                  
                  'Threshold',  objprec_expr,   ...
                  'ShowObjPer', objfreq_expr,   ...
                  'FwRes', true,                ...
                  'MaxIter', 1000,              ...
                  'UseResidual', false,         ...                  
                  'InitModel', init_model );

elseif( isequal( desc_name, 'dppca_vp' ) )
    model ...
     = feval(     fn_model, X, dim_Z,             ...
                  Vp,    adj_Network,             ...
                  'W_GT',        W_GT,            ...
                  'ZeroMean',    b_zeromean_expr, ...    
                  'Eta',         ETA,             ...                  
                  'Threshold',   objprec_expr,    ...
                  'ShowObjPer',  objfreq_expr,    ...
                  'VaryETA',     true,            ...
                  'MaxIter',     1000,            ...
                  'UseResidual', true,            ...
                  'InitModel',   init_model           );

else
    model ...
     = feval(     fn_model, X, dim_Z,             ...
                  Vp, adj_Network,                ...
                  'ModelType',   desc_name,      ...
                  'W_GT',        W_GT,            ...
                  'ZeroMean',    b_zeromean_expr, ...    
                  'Eta',         ETA,             ...                  
                  'Threshold',   objprec_expr,    ...
                  'ShowObjPer',  objfreq_expr,    ...
                  'MaxIter',     1000,            ...
                  'UseResidual', false,           ...                  
                  'InitModel',   init_model );
end

end

